### ISSUE TITLE
about decoupling rotation and translation

### ISSUE THREAD

**Issue by CUIMD** [ApdowJN/Stereo-NEC#1]
Question: In which part of the ORB-SLAM3 is the operation of decoupling rotation and translation added? Is his purpose to increase accuracy? Because it works together with joint BA optimization, it actually takes longer. Thank you very much for your answer

I am looking forward to your code being open-source

**Comment by ApdowJN** [comment]
Hi, thank you for your interest in our work! 

1. In response to your first question about where we integrate our rotation-translation decoupled optimization into ORB-SLAM3.
We implemented rotation-translation decoupled optimization in a function named 'InitializeIMU' within the local mapping thread. Initially, we estimate gyroscope bias using normal epipolar constraints. Subsequently, we update the rotation estimation by integrating IMU data with the gyroscope bias removed from gyroscope measurements. Then, we apply a 3-DoF bundle BA on translation only, which involves fixing rotation and map points in BA.

2. Is this purpose to increase accuracy?
We made this decision based on our observation that the rotation obtained through IMU rotation integration, after eliminating the gyroscope bias, is more accurate compared to the rotation derived solely from visual SLAM in the EuRoC dataset. Once a good rotation estimation is achieved, it helps to estimate the translation accuracy as well. (Please refer to Table I of our paper for details).

3. Once you have a good initial estimation of rotation, translation, and IMU bias, it will accelerate your VI-BA process.

We will open-source our code soon.

**Comment by CUIMD** [comment]
In the drt vio paper, the Bias Estimator did not spend much time

**Comment by ApdowJN** [comment]
This related to implementation, specifically the time-consuming is from gyroscope bias estimation. 
Since we integrate our method into ORB-SLAM3, we need to introduce additional steps like optical flow with RANSAC for tracking keypoints between two consecutive frames, resulting in increased processing time. 

When applied in our own SLAM system, which is developed based on VINS-Fusion, the Bias, Vel&Grav Est process is significantly faster (similar to ORB-SLAM3) due to existing data association between consecutive frames, already available in feature_tracker.cpp. We've only open-sourced the method in the ORB-SLAM3 version for demonstrating the concept and will not release the code version used in our own SLAM system which is used for product.
