### ISSUE TITLE
frame creation error

### ISSUE THREAD

**Issue by HJMGARMIN** [ApdowJN/Stereo-NEC#10]
Great work!
I met a problem at line 200 of the file Frame.cc as follows: 
![image](https://github.com/ApdowJN/Stereo-NEC/assets/52454672/956cff2e-7a5e-4e83-9aea-a0367dc923cf)
When I run the example, a problem occured!
![image](https://github.com/ApdowJN/Stereo-NEC/assets/52454672/cad30cb9-478e-42bb-8768-71a9de861c12)
The problem looks strange and I don't know how to solve it. Can you help me?

**Comment by ApdowJN** [comment]
Thank you for your interest! I haven't encountered this error before, but I suspect it's not an issue with frame.cc since you printed out 'frame ok'. You could try restarting a terminal, killing the previous processes, and then running it again. I suspect it might be an issue with some previous memory not being fully released.

**Comment by HJMGARMIN** [comment]
I soved it by changing the version of OpenCV. The version of OpenCV should be same as the version of ROS(Melodic->OpenCV 3).
