### ISSUE TITLE
where can I find the corresponding code of ".Joint Visual-Inertial Bundle Adjustment"

### ISSUE THREAD

**Issue by HJMGARMIN** [ApdowJN/Stereo-NEC#11]
Dose the following code contains the process of "computing the average residual of the
normal epipolar constraint"?
![image](https://github.com/ApdowJN/Stereo-NEC/assets/52454672/bb3ae473-e057-41c4-b78e-fdec4abf30c8)
![image](https://github.com/ApdowJN/Stereo-NEC/assets/52454672/38f74596-adf4-4cc1-8cfa-0033eef7c634)

**Comment by ApdowJN** [comment]
The code displayed in your screenshot performs joint VI-BA. The released version of the code, which includes only the initialization methods and how to evaluate in terms of ATE and RRE, continuously triggers initialization until the end of the sequences. We apply the condition for successful initialization in our own SLAM system rather than in ORB-SLAM3, as we use it to demonstrate the concept. However, this is not difficult because the normal vectors, the IMU-CAM extrinsic parameters, and updated translation have already been provided in previous steps. If you need the code for the condition, I can send it to you via email or WeChat (mine is add_executable_wwh).

**Comment by HJMGARMIN** [comment]
Thanks for your sharing.(my e-mail: garminx@foxmail.com)
